
name: alpine

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build --build-arg CMAKE_DOWNLOAD_ARTIFACT_TOKEN=${{ secrets.CMAKE_DOWNLOAD_ARTIFACT_TOKEN }} --tag ghcr.io/kwopin/internal/alpine:$GITHUB_SHA alpine
          docker tag ghcr.io/kwopin/internal/alpine:$GITHUB_SHA ghcr.io/kwopin/internal/alpine:latest
          docker push ghcr.io/kwopin/internal/alpine
