name: android-emulator

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull ghcr.io/kwopin/helpers/android-emulator:latest
          docker build --tag ghcr.io/kwopin/helpers/android-emulator:$GITHUB_SHA --cache-from ghcr.io/kwopin/helpers/android-emulator:latest android-emulator
          docker tag ghcr.io/kwopin/helpers/android-emulator:$GITHUB_SHA ghcr.io/kwopin/helpers/android-emulator:latest
          docker push ghcr.io/kwopin/helpers/android-emulator
