
name: docker

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-focal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull ghcr.io/kwopin/internal/ubuntu-focal:latest
          docker build --tag ghcr.io/kwopin/internal/ubuntu-focal:$GITHUB_SHA --cache-from ghcr.io/kwopin/internal/ubuntu-focal:latest ubuntu-focal
          docker push ghcr.io/kwopin/internal/ubuntu-focal:$GITHUB_SHA

  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull ghcr.io/kwopin/internal/alpine:latest
          docker build --tag ghcr.io/kwopin/internal/alpine:$GITHUB_SHA --cache-from ghcr.io/kwopin/internal/alpine:latest alpine
          docker push ghcr.io/kwopin/internal/alpine:$GITHUB_SHA
